
package liuyang.testcxf.modules.client.hello.aliyun.dns.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-03-17T16:21:34.706+08:00
 * Generated source version: 3.4.3
 *
 */
public final class HelloInterface_HelloServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.server.modules.testcxf.liuyang/", "HelloServiceService");

    private HelloInterface_HelloServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HelloServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloServiceService ss = new HelloServiceService(wsdlURL, SERVICE_NAME);
        HelloInterface port = ss.getHelloServicePort();

        {
        System.out.println("Invoking sayHello...");
        String _sayHello_arg0 = "";
        int _sayHello_arg1 = 0;
        String _sayHello__return = port.sayHello(_sayHello_arg0, _sayHello_arg1);
        System.out.println("sayHello.result=" + _sayHello__return);


        }
        {
        System.out.println("Invoking foo...");
        String _foo__return = port.foo();
        System.out.println("foo.result=" + _foo__return);


        }

        System.exit(0);
    }

}
